theme = "plain"
icons = "awesome"

#[[block]]
#block = "disk_space"
#path = "/"
#alias = "/"
#info_type = "available"
#unit = "GB"
#interval = 20
#warning = 20.0
#alert = 10.0

#[[block]]
#block = "focused_window"
#max_width = 21

#[[block]]
#block = "net"
#device = "wlp3s0"
#ssid = true
#ip = true
#speed_up = true
#interval = 1
#use_bits = true

[[block]]
block = "net"
device = "wlp3s0"
ip = true
speed_up = true
interval = 1
use_bits = true

#[[block]]
#block = "xrandr"
#icons = true
#resolution = true
#interval = 2

#[[block]]
#block = "nvidia_gpu"
#label = "RTX 2070"
#show_memory = true
#show_clocks = true
#show_temperature = true
#interval = 1

[[block]]
block = "temperature"
interval = 10
collapsed = false
format = "{max}° max, {average}° avg"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "sound"

[[block]]
block = "weather"
format = "{weather} ({location}) {temp}°"
service = { name = "openweathermap", api_key = "6dc001f4e77cc0985c5013283368be51", city_id = "5336269", units = "metric" }

[[block]]
block = "time"
interval = 1
format = "%a %m/%d %R"
