#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "jellybeans"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    relativenumber = false
    enable_vimfiler_gitstatus = true
    filemanager = "nerdtree"
    autoread = true
    bootstrap_after = "myconfig#after"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'git'

[[layers]]
name = 'VersionControl'

[[layers]]
name = 'lang#python'

[[layers]]
name = 'lang#php'

[[layers]]
name = 'lang#html'

[[layers]]
name = 'lang#rust'

[[layers]]
name = 'lang#lisp'

[[layers]]
name = 'ui'

[[layers]]
name = 'sudo'

[[layers]]
name = 'colorscheme'

[[layers]]
name = 'fzf'

[[layers]]
name = 'tools'

[[custom_plugins]]
name = 'PProvost/vim-ps1'

[[custom_plugins]]
name = 'saltstack/salt-vim'
