add_newline = false
command_timeout = 1000

[directory]
truncate_to_repo = false

[time]
disabled = false
utc_time_offset = "-7"
format = "[$time]($style) "

[hostname]
ssh_only = false
format = "[$hostname]($style) "

[cmd_duration]
disabled = true

[username]
show_always = true
format = "[$user]($style)@"
